mysite/mysite/urls.py
# -*- coding: utf-8 -*-
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import RedirectView
from mysite.settings import MEDIA_ROOT, MEDIA_URL
from debug_toolbar.toolbar import debug_toolbar_urls
from schema_graph.views import Schema

# from polls.views import InputForm
handler404 = "polls.views.handler404"
urlpatterns = [
    path("", RedirectView.as_view(url="/learn/http/"), name="home"),
    path("account/", include("django.contrib.auth.urls")),
    path("learn/", include("learning.urls")),
    # path("", InputForm.as_view(), name="form"),
    path("polls/", include("polls.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("schema/", Schema.as_view()),
] + debug_toolbar_urls()

urlpatterns = urlpatterns + static(MEDIA_URL, document_root=MEDIA_ROOT)

mysite/polls/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.views.generic.dates import ArchiveIndexView, YearArchiveView
from . import views
from polls.models import Question

# urlpatterns = [
#     path("", views.index, name="index"),
#     path("<int:question_id>", views.detail, name="details"),
#     path("<int:question_id>/results", views.results, name="results"),
#     path("<int:question_id>/vote", views.vote, name="vote"),
# ]

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("vote", views.vote, name="vote"),
    path("add", views.PollsCreate.as_view(), name="polls-create"),
    path("users", views.PollsUsers.as_view(), name="polls-users"),
    path(
        "archive_index/",
        ArchiveIndexView.as_view(
            model=Question,
            date_field="created",
            paginate_by=100,
            context_object_name="latest",
        ),
        name="archive-index",
    ),
    path(
        "archive_index/<int:year>",
        views.QuestionYearArchiveView.as_view(),
        name="archive-index-year",
    ),
    path(
        "archive_index/<int:year>/<str:month>",
        views.QuestionMonthArchiveView.as_view(),
        name="archive-index-month",
    ),
]

mysite/learning/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django_extensions.db.models import TitleDescriptionModel


# Create your models here.
class TablespaceExample(models.Model):
    name = models.CharField(max_length=30, db_index=True, db_tablespace="indexes")
    data = models.CharField(max_length=255, db_index=True)
    shortcut = models.CharField(max_length=7)
    edges = models.ManyToManyField(to="self", db_tablespace="indexes")

    class Meta:
        db_tablespace = "tables"
        indexes = [models.Index(fields=["shortcut"], db_tablespace="other_indexes")]


class Topping(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Pizza(models.Model):
    name = models.CharField(max_length=50)
    toppings = models.ManyToManyField(Topping, related_name="pizza")

    def __str__(self):
        return "%s (%s)" % (
            self.name,
            ", ".join(topping.name for topping in self.toppings.all()),
        )


class Restaurant(models.Model):
    pizzas = models.ManyToManyField(Pizza, related_name="restaurants")
    best_pizza = models.ForeignKey(
        Pizza, related_name="championed_by", on_delete=models.CASCADE
    )


class PdfFileModel(TitleDescriptionModel):
    pdf = models.FileField(upload_to="pdfs")

    def __str__(self):
        return "{title} Pdf".format(title=self.title)

mysite/templates/stock/back_to_top.html
<div class="back-to-top">
    <a href="#main" type="button" class="button text-decoration-none">
        <i class="fa fa-arrow-up"></i> Back To Top
    </a>
</div>

mysite/templates/stock/error.html
Error Occured With Status Code = {{ response_error.status_code }}

mysite/templates/stock/error_message.html
{% load static %}
{% block error_block %}
{% if form.errors %}
<div id="error_block">
    <div class="toast-container position-fixed bottom-0 end-0 p-3" id="toastContainer">
        <div id="liveToast" class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true"
            data-autohide="true">
            <div class="toast-header">
                <img src="{% static 'images/polls.png' %}" class="rounded me-2" alt="polls_error" width="32"
                    height="32">
                <strong class="me-auto">Polls Error</strong>
                <small>Recently</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                {% for field in form %}
                {% for error in field.errors %}
                <strong>{{ error|escape }}</strong>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <strong>{{ error|escape }}</strong>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}
{% block error_script_js %}
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const toast = document.getElementById("toastContainer");
        setTimeout(() => {
            if (toast) {
                toast.style.display = "none";
            };
        }, 3000);
    });
</script>
{% endblock %}

mysite/templates/stock/pagination.html
{% block pagination %}
<nav aria-label="Page navigation mx-auto">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item"><span class="page-link">Page {{ page_obj.number }} of
                {{page_obj.paginator.num_pages}}.</span></li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                Next
            </a>
        </li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages}}">Last</a></li>
        {% endif %}
    </ul>
</nav>
{% endblock %}

mysite/templates/stock/polls_filter.html
{% load static %}
{% block polls_filter %}
<div class="container">
    <div class="row">
        <button type="button" class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#pollsFilter"
            aria-expanded="false" aria-controls="pollsFilter">
            <span class="fa fa-cog"></span> Advance Polls Filter
        </button>
        <div class="collapse my-3" id="pollsFilter">
            <div class="card card-body">
                <form class="form-inline" role="form" method="get" id="pollsFilterForm">
                    <div class="form-group mb-3">
                        <label class="form-label" style="margin-right:0;" for="polls-perpage">Rows per page:</label>
                        <select id="polls-perpage" class="form-control">
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option selected="selected" value="10">10</option>
                            <option value="15">15</option>
                            <option value="20">20</option>
                        </select>
                    </div>
                    <div class="form-group mb-3">
                        <label class="form-label" style="margin-right:0;" for="polls-orderby">Order by:</label>
                        <select id="polls-orderby" class="form-control">
                            <option value="-created">Newest First</option>
                            <option value="created">Oldest First</option>
                            <option value="?">Random Polls</option>
                        </select>
                    </div>
                    <div class="form-group mb-3">
                        <label class="form-label" style="margin-right:0;" for="polls-tag">Select Tag:</label>
                        <select id="polls-tag" class="form-control text-capitalize">
                            <option class="" value="">None</option>
                            {% for tag in tags %}
                            <option class="" value="{{tag}}">{{tag}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary" id="filterFormBtn"
                        onclick="submitFilterPollsForm(event)">Filter Data</button>
                    <button type="reset" class="btn btn-primary" id="filterFormBtnReset">Reset
                        Data</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block polls_filter_js %}
{% endblock %}

mysite/templates/stock/preload.html
{% block preloader %}
<div class="preloader d-flex align-items-center justify-content-center bg-light" style="height: 100vh;">
    <div class="loader">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
{% endblock %}

mysite/templates/stock/side_navbar.html
{% load static %}
{% block sidenav %}
<div class="card" id="sidebar">
    <div class="card-header">
        <div class="d-flex align-items-center text-decoration-none">
            <div class="card-body text-center">
                <div class="card-body text-center">
                    <!-- img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar" -->
                    {% if user.profile %}
                    <img src="{{user.profile.url}}" alt="avatar" class="rounded-circle img-fluid border border-3 p-2"
                        style="width: 150px;">
                    {% else %}
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava2-bg.webp" class=""
                        alt="avatar" width="100" />
                    {% endif %}
                    <h5 class="my-3">{{user.first_name}} {{user.last_name}}</h5>
                    <p class="text-muted">{{user.address}}</p>
                    Date: {% now "jS M Y, h:m:s" %}
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="list-group">
            <a type="button" href="{% url 'index' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == '/polls/' %} active {% endif %}"
                aria-current="true">
                <i class="fa fa-home"></i>
                Home
            </a>
            <a type="button" href="{% url 'send_email' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == '/polls/' %} active {% endif %}"
                aria-current="true">
                <i class="fa fa-home"></i>
                Send Email
            </a>
            <a type="button" href="{% url 'pdf-lists' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == 'polls/tags/' %} active {% endif %}">
                <i class="fa fa-tag"></i>
                Pdfs List
            </a>
            <a type="button" href="#"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == 'polls/tags/' %} active {% endif %}">
                <i class="fa fa-tag"></i>
                Tags
            </a>
            {% comment %}
            {% if perms.learn.add_pizza %}
            {% endcomment %}
            <a type="button" href="/learn/pizaa_add"
                class="list-group-item list-group-item-action rounded text-capitalize fs-5 border-0 px-4 {% if request.url == 'learn/pizaa_add/' %} active {% endif %} ">
                <i class="fa fa-tag"></i>
                pizza add
            </a>
            {% comment%}
            {% endif %}
            {% endcomment %}
            <a type="button" href="{% url 'polls-create' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == 'polls/tags/' %} active {% endif %}">
                <i class="fa fa-square-poll-vertical"></i>
                Create Polls
            </a>
            {% if request.user.is_authenticated %}
            <a type="button" href="{% url 'profile' user.id %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == 'accounts/profile/' %} active {% endif %}">
                <i class="fa fa-user"></i>
                Profile
            </a>
            {% if request.user.is_superuser %}
            <a type="button" href="/admin"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == 'accounts/profile/' %} active {% endif %}">
                <i class="fa fa-user-tie"></i>
                Admin
            </a>
            <a type="button" href="/polls/users"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == 'accounts/profile/' %} active {% endif %}">
                <i class="fa fa-user-tie"></i>
                Available Users
            </a>
            {% endif %}
            <a type="button" href="{% url 'password_change' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == '/accounts/logout/' %} active {% endif %}">
                <i class="fa fa-arrow-right-from-bracket"></i>
                Password Change
            </a>
            <a type="button" href="{% url 'password_reset' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == '/accounts/logout/' %} active {% endif %}">
                <i class="fa fa-arrow-right-from-bracket"></i>
                Password Reset
            </a>
            <a type="button" href="{% url 'password_reset_complete' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == '/accounts/logout/' %} active {% endif %}">
                <i class="fa fa-arrow-right-from-bracket"></i>
                Password Reset Complete
            </a>
            <a type="button" href="{% url 'logout' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == '/accounts/logout/' %} active {% endif %}">
                <i class="fa fa-arrow-right-from-bracket"></i>
                Logout
            </a>
            {% else %}
            <a type="button" href="{% url 'login' %}"
                class="list-group-item list-group-item-action rounded fs-5 border-0 px-4 {% if request.url == '/accounts/login/' %} active {% endif %}">
                <i class="fa fa-arrow-right-to-bracket"></i>
                Login
            </a>
            {% endif %}
        </div>
    </div>
</div>
<!-- Sidebar -->

{% endblock %}

mysite/templates/stock/theme_toggle.html
{% block theme_toggle %}
<div class="theme-bg">
    <!-- Theme Toggle Start -->
    <div class="theme-toggle position-fixed bottom-0 end-0 m-3 bg-primary rounded-circle p-3" style="z-index: 1000;">
        <label class="switch">
            <input type="checkbox" name="theme" id="theme" checked />
            <span class="slider"></span>
        </label>
    </div>
    <!-- Theme Toggle End -->
</div>
{% endblock %}